def build(bld):
    bld.DefineGem(
        # Add custom build options here
        includes = [
			bld.Path('Code/CryEngine/CryAction')
		],
		defines = [
			'SQLITE_ENABLE_FTS5',
			'SQLITE_ENABLE_JSON1',
			'SQLITE_ENABLE_RTREE',
			'SQLITE_ENABLE_RBU',
			#'SQLITE_ENABLE_ICU',
			'SQLITE_THREADSAFE=1',
			'SQLITE_OMIT_DEPRECATED'
		],
		release_defines = [
			'SQLITE_DEFAULT_MEMSTATUS=0'
		],
        win_features = ['crcfix']
    )
